/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#0050cb',
        'primary-container': '#0066ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#f8f7ff',
        'primary-fixed': '#dae1ff',
        'primary-fixed-dim': '#b3c5ff',
        'inverse-primary': '#b3c5ff',
        secondary: '#4648d4',
        'secondary-container': '#6063ee',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'secondary-fixed': '#e1e0ff',
        'secondary-fixed-dim': '#c0c1ff',
        tertiary: '#006645',
        'tertiary-container': '#008259',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#e1ffec',
        surface: '#faf8ff',
        'surface-dim': '#d8d9e6',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#ecedfa',
        'surface-container-high': '#e6e7f4',
        'surface-container-highest': '#e1e2ee',
        'surface-variant': '#e1e2ee',
        'surface-tint': '#0054d6',
        'on-surface': '#191b24',
        'on-surface-variant': '#424656',
        'inverse-surface': '#2e303a',
        'inverse-on-surface': '#eff0fd',
        outline: '#727687',
        'outline-variant': '#c2c6d8',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#faf8ff',
        'on-background': '#191b24',
        'slate-50': '#F8FAFC',
        'slate-100': '#F1F5F9',
        'slate-800': '#1E293B',
        'slate-900': '#0F172A',
        'glass-stroke': 'rgba(255,255,255,0.12)',
        'accent-blue-soft': '#E0EBFF',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        geist: ['Geist', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        base: '8px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '24px',
        'margin-mobile': '16px',
      },
      backdropBlur: { md: '12px', lg: '20px' },
      boxShadow: {
        card: '0 1px 3px rgba(0,0,0,0.04), 0 1px 2px rgba(0,0,0,0.06)',
        'card-hover': '0 4px 16px rgba(0,80,203,0.10)',
        glass: '0 8px 32px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
};
